# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: News Crawler

on:
  schedule:
     - cron:  '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install chrome
      run: |
        sudo apt-get install unzip chromium-browser
        sudo wget https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip
        sudo chmod +x chromedriver
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Crawler
      run: python crawler.py
      working-directory: ./crawler
